azinformatica/loki

src/components/AzAbout.vue
src/components/AzAside.vue
src/components/AzAvatar.vue
src/components/AzLogo.vue
src/components/AzMenu.vue
src/components/AzTitle.vue
src/index.js
test/unit/AzAbout.test.js
test/unit/AzAside.test.js
test/unit/AzAvatar.test.js
test/unit/AzLogo.test.js
test/unit/AzMenu.test.js
test/unit/AzTitle.test.js

Renamed all occurrences of word **wids** to **loki**

Renamed all occurrences of word "wids" to "loki"

---

README.md

Added npm badge to README

---

package.json
src/components/search/AzSearch.vue

Refatoração busca avançada.

---

src/components/layout/AzMenu.vue

- correção no hover do azMenu
- ajuste para quando um submenu estiver selecionado e a pagina for recarregada, o meu pai vir expandido

Ajustes no AzMenu

---

src/components/actions/AzCallToAction.vue

ajuste para não reclamar da propriedade class no componente azCallToAction

AzCallToAction

---

package-lock.json
package.json
src/components/file/AzDocumentViewer.vue
src/components/layout/AzAside.vue
src/components/layout/AzAvatar.vue
src/components/layout/AzLogo.vue
src/components/layout/AzMenu.vue
src/components/layout/AzTemplate.vue
src/components/layout/templates/AzTemplateDefault.vue
src/components/layout/templates/AzTemplateGmail.vue
src/index.js

- Possibilidade de criar templates diferentes para as aplicações
- Componente para visualização de documentos AzDocumentViewer

Templates e AzDocumentViewer

---

src/components/layout/AzAlert.vue
src/components/layout/AzAvatar.vue
src/components/layout/AzNotification.vue
src/components/layout/templates/AzTemplateDefault.vue
src/components/layout/templates/AzTemplateGmail.vue
src/components/layout/templates/AzTemplateVader.vue
src/filters/elapsed-time.js
src/index.js
src/store/mutations-types.js
src/store/mutations.js
src/store/state.js

- renomeei o componente AzNotification -> AzAlert
- implementação do componente de notificação para mensagens para o usuário (AzNotification)

AzNotification e AzAlert

---

package.json
src/components/file/AzDocumentViewer.vue

- mudança na posição do indicador de páginas para não atrapalhar a leitura em monitores pequenos
- ajuste no controle das páginas ao entrar na viewport

AzDocumentViewer

---

src/components/layout/AzNotification.vue

Ajuste para não mostrar o texto do final da lista do infinite-scrolling

AzNotification

---

package-lock.json
src/components/layout/AzAvatar.vue
src/components/layout/AzMenu.vue
src/directives/auth.js
src/index.js
src/utils/az-auth.js

- Utilitário para verificar permissões
- Permissões nos menus (avatar e aside)

Permissões

---

src/components/file/AzDocumentViewer.vue
src/components/layout/templates/AzTemplateGmail.vue

[AzDocumentViewer]
- escondendo o label de paginacao no mobile
- possibilidade de utilizar o zoom no mobile
- ajuste na propriedade de scroll no overflow do componente
[AzTemplateGmail]
- logo na toolbar para mobile
- propriedade para esconder a ação principal

AzDocumentViewer e AzTemplateGmail

---

src/components/layout/templates/AzTemplateGmail.vue

[AzTemplateGmail]
- logo na toolbar APENAS para mobile

AzTemplateGmail

---

src/store/actions.js
src/store/mutations.js

- corrigi para setar o arquivo do upload com erro

[AzFileProgress]

---

src/components/layout/AzAvatar.vue
src/components/layout/templates/AzTemplateDefault.vue

- Alterações para apresentar o domain do usuário.
- Alterações no template default para apresentar as notificações e uma área livre no menu lateral.

Alterações nos componentes de Avatar e Template default.

---

src/components/file/AzFileUpload.vue
src/components/layout/AzLogo.vue

- Quando clicar na logo no menu lateral, deve redirecionar para a tela principal do sistema: path: '/'

Retirei o console.log('Go') e redirecionei para o path principal da aplicação.

---

src/components/form/AzForm.vue
src/components/form/AzMoney.vue
src/components/layout/AzContainer.vue

- Correção do az-money para emitir o evento somente quando o valor for diferente do que já existia;
- Correção de CSS da componente de .az-table-list, para estilizar .v-table para personalizar o padding.

- Correção do az-money

---

src/components/form/AzMoney.vue

- emissão de eventos on-blur;
- botão para limpar campo.

Az-money: permitir valores nulos.

---

LICENSE
src/components/form/AzMoney.vue

- Correção no componente az-money para o valor do value ser "null" por default.
- Adição do arquivo de LICENSE.

- Correção no componente az-money e arquivo de LICENSE.

---

package.json

- Resolvido a issue ```#89 - Potential security vulnerability in webpack-dev-server```.

solved issue #89

---

package.json

Remoção do plugin do jest, pois estava afetando os testes em projetos que usam o loki

Remoção do plugin do jest

---

src/components/viewer/AzPdfDocumentViewer.spec.js
src/components/viewer/AzPdfDocumentViewer.vue
src/components/viewer/AzPdfDocumentViewerPage.spec.js

- correção na páginação
- correção de testes do componente principal
- correção de testes do componente de páginas

Bugfix AzPdfDocumentViewer

---

.all-contributorsrc
README.md
package.json
src/components/form/AzDateSimple.vue

- Updating the az-date-simple component to display the date/time;
- Update of package.json version;
- Update of readme.md;
- Added the .all-contributorsrc file.

Correction in the az-date-simple component to display the date/time.

---

src/components/form/AzComboEnum.vue

Inserido props selecione em AzComboEnum para inserir ou retirar objeto selecione no select

Inserido props selecione em AzComboEnum

---

docs/docs/getting-started/quick-start.md
docs/website/blog/2020-02-18-version-1.0.1-release.md
docs/website/blog/2020-02-18-version-1.0.2-release.md
docs/website/blog/2020-02-18-version-1.0.3-release.md
docs/website/blog/2020-02-18-version-2.0.2-release.md
docs/website/core/Footer.js
docs/website/pages/en/help.js
docs/website/pages/en/index.js
docs/website/static/css/custom.css

- Update of the releases blog;
- Update of the documentation of quick start.

Update of the releases blog

---

package.json
src/components/form/AzDate.vue
src/components/form/AzMoney.vue

Correção no az-date que estava enviando um evento de input ao carregar o componente, ativando assim a validação do vee-validate
Alterado componente az-money para apresentar mensagem de validação com o vee-validate

Correção no az-date e az-money

---

package.json
src/components/form/AzDate.vue

Alteração no az-date para apresentar o campo de data com a cor de erro enquanto o usuario estiver preenchendo uma data invalida

Alteração no az-date

---

package.json
src/components/layout/AzMenu.vue

[BUGFIX] Correção no copomente az-menu para melhorar o posicionamento dos icones e texto em sub menus

[BUGFIX] Correção no copomente az-menu

---

src/components/layout/AzAvatar.spec.js
src/components/layout/AzMenu.vue
src/components/search/AzSearch.spec.js
src/components/viewer/AzPdfDocumentViewer.spec.js
src/filters/elapsed-time.spec.js

- Update CSS az-menu;
- Update unit tests.

- Update unit tests and CSS.

---

src/components/viewer/AzPdfDocumentViewer.spec.js
src/components/viewer/AzPdfDocumentViewer.vue
src/components/viewer/AzPdfDocumentViewerPage.spec.js
src/components/viewer/AzPdfDocumentViewerToolbar.spec.js
src/components/viewer/AzPdfDocumentViewerToolbar.vue
src/store/action-types.js
src/store/actions.js
src/store/state.js

Implementado correções e melhorias feitas na branch stable para o componente e correção nos testes unitários.

[Bugfix] AzPdfDocumentViewer

---

src/components/form/AzComboEnum.vue
src/components/form/AzDate.vue
src/components/form/AzForm.vue
src/components/form/AzMoney.vue

[FEATURE] Adição do slot de labal nos componentes AzComboEnum, AzDate e AzMoney

[FEATURE] Adição do slot de labal nos componentes AzComboEnum, AzDate e AzMoney

---

src/components/form/AzComboEnum.vue
src/components/form/AzDate.vue
src/components/form/AzForm.vue
src/components/form/AzMoney.vue
src/components/layout/AzAutoSave.vue
src/components/layout/AzAvatar.vue
src/components/layout/AzMenu.vue
src/components/search/AzSearch.spec.js
src/components/search/AzSearch.vue
src/store/mutations.js

[BUGFIX] Correção do componente az-date e az-money que não estavam funcionando dentro de listas
[BUGFIX] Correção do componente az-money para permitir adicionar mensagem de obrigatoriedade personalizada
[FEATURE] Adição dos slots de append e append-outer nos componentes AzComboEnum, AzDate e AzMoney

Correções e slotes

---

package.json
src/components/form/AzForm.vue
src/components/form/AzMoney.vue
src/components/search/AzSearch.vue
src/components/search/AzToolbar.vue

[FEATURE] Alteração nos componentes AzMoney, AzSearch, AzToolbar e AzForm para melhorar a responsividade do sistema.

Alteração para atender o sistema patrimonio-intangivel

---

package.json
src/components/form/AzDate.vue

[FEATURE] Alteração nos componentes AzDate para adicionar a validação de data minima, maxima e data invalida.

Alteração nos componente AzDate

---

package.json
src/components/form/AzDate.vue

[BUGFIZ] Correção no componente AzDate pois estava apresentando erro quando data era vazia

[BUGFIZ] Correção no componente AzDate

---

package.json
src/components/form/AzDate.vue

[BUGFIZ] Correção no componente AzDate pois estava apresentando erro quando data era vazia

Correção no componente AzDate

---

package.json
src/components/form/AzDate.vue

[FEATURE] Alteração no componente AzDate para melhorar a experiencia de preenchimento do campo apenas pelo teclado. Adicionado tab index no botão referente ao modal para ser ignorado durante o preenchimento pelo teclado

Alteração no componente AzDate

---

package.json
src/components/layout/AzLoading.vue

[BUGFIX] Alteração no componente az-loading que não fechava em algumas situações

Alteração no componente az-loading

---

package.json
src/components/viewer/AzPdfDocumentViewer.spec.js
src/components/viewer/AzPdfDocumentViewer.vue
src/components/viewer/AzPdfDocumentViewerPage.spec.js
src/components/viewer/AzPdfDocumentViewerPage.vue
src/store/action-types.js
src/store/actions.js

- Code refactoring
- Fix the unit tests with console error
- Improves the next or previous pages rendering
- Fix the error "cannot use the same canvas during rendering"

[FEATURE] Pdf Rendering Fit to Page in mobile devices

---

package.json
src/index.js
src/store/action-types.js
src/store/actions.js
src/store/mutation-types.js
src/store/mutations.js
src/store/state.js
src/utils/AzDigitalSignature.js
src/utils/AzDigitalSignature.spec.js

Adiciona classe utilitária pra fazer assinatura digital integrado com api do flowbee.

Assinatura Digital

---

package.json
src/store/actions.js

- correção de bug ao finalizar assinatura digital
- refatorações nos métodos

Correção no método de assinatura digital

---

package.json
src/store/actions.js
src/utils/AzDigitalSignature.js

Adiciona opção de enviar imagem de rúbrica ao realizar assinatura digital

Assinatura digital com rúbrica

---

package.json
src/components/viewer/AzPdfDocumentViewer.spec.js
src/components/viewer/AzPdfDocumentViewer.vue
src/components/viewer/Toolbar.vue
src/store/action-types.js
src/store/actions.js

- fix css import at azPdfDocumentViewer
- download method emit an event to be resolved in the application

[HOTFIX] style import and change download feature

---

package.json
src/components/viewer/Toolbar.vue

Change comparition statement in the "changeScaleType" action button. This change permit pass the property ''defaultScaleType" with values: page-width, page-fit(default) and auto.

AzPdfDocumentViewer

---

package.json
src/components/layout/AzAlert.vue
src/components/layout/AzAside.spec.js
src/components/search/AzSearch.vue
src/components/viewer/AzPdfDocumentViewer.spec.js
src/store/mutations.js

Creio que com esse limite o componente não extrapola os limites do filtro, oque estava acontecendo no projeto Mobiliario.

[MELHORIA]/ Limite de carácteres  no AzSearch

---

package.json
src/components/viewer/AzPdfDocumentViewer.spec.js
src/components/viewer/AzPdfDocumentViewer.vue

- added support to navigate on click upon internal links (chapters, topics, referenced pages).

Feature - Navigation on click upon internal links

---

src/components/actions/AzCallToAction.spec.js
src/components/actions/AzCallToAction.vue

Adicionado a funcionalidade do botão desabilitado com o acompanhamento do devido CSS.

Update AzCallToAction - Disabled button

---

src/components/layout/AzAlert.vue
src/components/layout/templates/AzTemplateDefault.vue
src/components/layout/templates/AzTemplateGmail.vue
src/components/layout/templates/AzTemplateVader.vue

- changes deprecated component `v-content` to `v-main`
- code formatting
- defines property `iconColor`

Bugfix and maintenances

---

package.json
src/components/viewer/AzPdfDocumentViewer.vue
src/components/viewer/Toolbar.vue

- centralizes toolbar control buttons
- added responsivity at mobile devices when has action buttons
- validation to not change the zoom when resize the window

Change - responsivity in the AzPdfDocumentViewer

---

package.json
src/components/viewer/Toolbar.vue
src/store/actions.js
src/utils/AzDigitalSignature.js

- added optional param to indicate the participation from signer
- only display "show more" button when toolbar has actions activated

Feature - participation param in the digital signature

---

package.json
src/components/layout/AzMenu.vue

Resolvido problema de navegação

Remoção de navegação duplicada no AzMenu

---

src/components/layout/AzAside.vue
src/components/layout/templates/AzTemplateDefault.vue

[FEATURE] Banner em menu lateral do componente "Aside"  (Stable)

---

src/components/form/AzDate.vue

- Correção na mask para adicionar os : após a hora
- Corrigido problema em que após selecionar minuto igual ao valor anterior não fechava o v-time-picker

Correção no campo hora do componente azDate

---

src/components/viewer/AzPdfDocumentViewer.spec.js
src/components/viewer/AzPdfDocumentViewer.vue

* Adicionando import pdf worker

[FIX] Adicionando import para funcionamento do azPdf

---

package.json
src/components/viewer/AzPdfDocumentViewer.spec.js
src/components/viewer/AzPdfDocumentViewer.vue
src/components/viewer/Draggable.spec.js
src/components/viewer/Draggable.vue

[FLOW-183](https://aztecnologia.atlassian.net/jira/software/c/projects/FLOW/boards/66?modal=detail&selectedIssue=FLOW-183)

[FEATURE] FLOW-183: Implementar copia de posicionamento no loki (stable)

---

package.json
src/components/viewer/AzPdfDocumentViewer.spec.js
src/components/viewer/AzPdfDocumentViewer.vue
src/components/viewer/Draggable.spec.js
src/components/viewer/Draggable.vue

[FLOW-183](https://aztecnologia.atlassian.net/jira/software/c/projects/FLOW/boards/66?modal=detail&selectedIssue=FLOW-183)

[FEATURE] FLOW-183: Implementar copia de posicionamento no loki (master)

---

src/components/form/AzMoney.vue

- Novas funcionalidades:
1. Adicionado suporte ao **data-vv-scope** para permitir validações dentro de escopos de formulário por meio da props com mesmo nome
2. Agora é possível alternar entre valores positivos e negativos clicando na tecla (**-**). Se clicado e o valor estiver negativo, o mesmo ficara positivo e vice-versa

[FEATURE]: Adicionado suporte ao data-vv-scope e permitir alterar sinal do valor por meio da tecla -

---

src/components/form/AzMoney.vue

- Mudança
1. A troca de sinal é realizada ao clicar nas teclas - ou +
- Funcionalidades
1. Adicionada props readonly do v-text-field

[CHANGE]: Ajuste do az-money para alterar o sinal do valor ao clicar em - ou +

---

src/components/viewer/AzPdfDocumentViewer.spec.js
src/components/viewer/AzPdfDocumentViewer.vue
src/directives/scroll.js
src/index.js

* Envolve [FLOW-248] (https://aztecnologia.atlassian.net/browse/FLOW-248)

Evento scroll visualizador pdf

---

package.json
src/utils/bpm/AzBpmProcess.js

* Correção no label do botão encaminhar ao chegar no fim da atividade no bpm;

Tratamento fim de atividade bpm
